[TOC]

# 何时中断线程？
+ 线程阻塞：阻塞表示线程的一种状态，在这种状态下，线程是不占用CPU的（也就是说，不执行你写的命令代码的，有些是让出CPU时间但是不让出锁），更进一步来说，也就是你的代码在执行过程中，在某个地方卡住了
+ 业务需要

# JAVA中断机制
<font color="red">在Java中，最好的停止线程的方式是使用中断interrupt，但是这仅仅是会通知到被终止的线程“你该停止运行了”，被终止的线程自身拥有决定权（决定是否、以及何时停止），这依赖于请求停止方和被停止方都遵守一种约定好的编码规范。</font>

## interrupt方法
+ interrupt()方法只是改变线程状态，而不是强制关闭线程
+ 被中断的线程它本身拥有响应中断的权利，因为有些线程的某些代码是非常重要的，我们必须要等待这些线程处理完成之后或者他们准备好之后，再由他们自己去主动终止，或者它们真的不想理会我们的中断这也是完全ok的，我们不应该鲁莽的使用stop方法，而是通过使用interrupt方法来发出一个信号，由它们自己处理，这样使我们的线程代码，在实际中更加安全，也完成了清理工作，数据的完整性也得到了保障

## InterruptedException
<font color="red">触发此异常会重置中断异常</font>
为何重置状态分为两步看：
1. 触发中断之前（业务 try catch）
2. 触发中断之后（善后 finally）,运行finally代码块，如果显示中断状态，那名不副实

# 两种中断机制
差别就在`checked exception`与`unchecked exception`：
1. 传递中断（优先选择）
2. 恢复中断状态（部分接口签名上没有抛出异常，不得已而为止）

## 传递中断（最优解）
<font color="red">添加异常到方法签名，在方法上抛出异常。</font>
用`throws InterruptedException`标记你的方法，不采用`try-catch`语句块捕获异常，以便于该异常可以传递到顶层，让顶层方法如`run`方法可以捕获这一异常
例如：
```java
void subTask() throws InterruptedException
    sleep(delay);
}
```

## 恢复中断（不得已而为之）
+ <font color="red">如果说接口的方法签名未抛出异常，那么实现该接口的方法就不能向上抛出异常</font>
+ 为了应对不能传递中断的情况（某些抽象方法体上未添加方法签名），我们就用向上抛出异常
+ 使用`Thread.currentThread().interrupt()`来恢复线程中断状态（注：被捕获之后状态会被重置）

在下面代码中：如果sleep被中断，就会触发`InterruptedException`，根据java的线程中断机制interruptStatus将会被重置。
如果没有throw异常将会被catch吞掉。所以重新将中断状态设置为中断，交由上层调用检查
```java
interface foo{
    /**
     * 因为此方法签名未抛出受检查异常，所以无法抛出
     */
    void bar();
}

public class RecoverInterrupt implements foo,Runnable {

    /**
     * 只能吞掉异常不能抛出，但是可以重置线程状态
     */
    @Override
    public void bar() {
        try {
            TimeUnit.SECONDS.sleep(5);
        } catch (InterruptedException e) { // 触发InterruptException会重置中断状态为false
            Thread.currentThread().interrupt();// 重置
            e.printStackTrace();
        }
    }

    @Override
    public void run() {
        while (true){
            if(Thread.currentThread().isInterrupted()){
                System.out.println("线程中断");
                break;
            }
            bar();
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Thread thread = new Thread(new RecoverInterrupt());
        thread.start();
        TimeUnit.SECONDS.sleep(1);
        thread.interrupt();
    }

}
```
未触发异常链，需手动更改状态，方便上游检查

# 不可中断的阻塞方法
拒绝被中断，这使得它们是不可取消的
下列代码展示了一个方法，该方法等待一个阻塞队列，直到队列中出现一个可用项目，而不管它是否被中断。
为了方便他人，它在结束后在一个 finally 块中恢复中断状态，以免剥夺中断请求的调用者的权利。
（它不能在更早的时候恢复中断状态，因为那将导致无限循环 —— BlockingQueue.take()将在入口处立即轮询中断状态，并且，如果发现中断状态集，就会抛出 InterruptedException。）

```java
public Task getNextTask(BlockingQueue<Task> queue) {
    boolean interrupted = false;
    try {
        while (true) {
            try {
                return queue.take();//这发生阻塞了
            } catch (InterruptedException e) {
                interrupted = true;
                // fall through and retry
            }
        }
    } finally {
        if (interrupted)
            Thread.currentThread().interrupt();
    }
}
```
## IO
<font color="red">无响应机制？</font>

并非所有的阻塞方法都抛出InterruptedException。输入和输出流类会阻塞等待I/O完成，但是它们不抛出InterruptedException，而且在被中断的情况下也不会提前返回。然而，对于套接字 I/O，如果一个线程关闭套接字，则那个套接字上的阻塞 I/O 操作将提前结束，并抛出一个 SocketException。

<font color="red">java.nio中的非阻塞I/O类也不支持可中断I/O，但是同样可以通过关闭通道或者请求Selector上的唤醒来取消阻塞操作。</font>

类似地，尝试获取一个内部锁的操作（进入一个synchronized块）是不能被中断的，但是ReentrantLock支持可中断的获取模式。

<font color="red">并不是所有的阻塞都是可中断的, 比如InputStream.read方法. 在检测到输入数据可用, 到达流末尾或者抛出异常前, 该方法一直阻塞. 而且阻塞的时候不会检查中断标记, 所以中断线程无法使read从阻塞状态返回. 但是关闭流可以使得read方法抛出异常, 从而从阻塞状态返回。</font>

例如：
```java
ServerSocket serverSocket = new ServerSocket(PORT);
Socket socket = serverSocket.accept();//阻塞函数
```
Socker.accept()一直在监听端口，一直阻塞在此处。他本身无法响应中断，如果启动一个守护线程来关闭也是可以的：硬关闭，socket.close()

一个情景（伪代码）：
```
method(){
    loop(true){//一直阻塞在此处，永远都走不到下面要执行响应中断的代码
        request()
    }
    while(isInterrupted){
        interrupt()
    }
}
```
## synchronized
synchronized不可被中断，但是wait可以
```java
public class CantInterruptSynchronized {

    static Object obj = new Object();

    public static void main(String[] args) {

        Runnable runnable = ()->{//lumbda创建对象依赖并受限于抽象函数接口
            synchronized (obj){
                System.out.println(Thread.currentThread().getName()+":拿到锁");
                for(;;){
                    System.out.println(Thread.currentThread().isInterrupted());
                }
            }
        };

        Thread thread1 = new Thread(runnable);
        thread1.setName("thread1");
        thread1.start();

        thread1.interrupt();

        Thread thread2 = new Thread(runnable);
        thread2.setName("thread2");
        thread2.start();

    }
}
```
## lock
lock也不行

# 尝试中断不可被中断的方法（包括长时间运行的方法、阻塞io）
## 方法一：设置超时时间
```java
public void method(){
    thread.start();
    join(time){
        print("老子不等了")
    }
}
```
## 方法二：设置守护线程
```java
public void main(){
    thread1.start();
    thread2.setMain(thread1);
    thread2.start();
}
thread1{
    run();
}
thread2{
    if(thread1.isinterrupted)
        thread.close()//这有点问题哈，如果线程是可中断的阻塞，那就没必要用，如果线程是bio类的，那么close；
}
```

# 使用volatile标记中断状态（具有局限性）【错误处理方式】
volatile变量标记的状态位发生变化不会立刻获取到中断请求，具体要看业务，如果已经进入到了执行方法内，此时发生中断，任务仍允许执行完毕，那就可以。反之，则中断无效

<font color="red">在中断检测之前或之后发生阻塞，走不到响应阻塞处理的代码</font>

<font color="red">“中断操作”作用于非阻塞方法，没啥意义，要的是如果阻塞了，可以通过某种机制响应中断，类似sleep这种都是一种即时处理</font>

```java
/**
 * 描述：
 * 演示用volatile的局限：part1 看似可行,实则不行
 */
public class WrongWayVolatile implements Runnable {

    private volatile boolean canceled = false;

    @Override
    public void run() {
        int num = 0;
        try {
            while (num <= 100000 && !canceled) {
                if (num % 100 == 0) {
                    System.out.println(num + "是100的倍数。");
                }
                num++;
                Thread.sleep(1);//阻塞时间短，不会发生在阻塞期间更改中断状态
//                Thread.sleep(100000);//阻塞时间长，此时发生中断状态更改，volatile无效
            }
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) throws InterruptedException {
        WrongWayVolatile r = new WrongWayVolatile();
        Thread thread = new Thread(r);
        thread.start();
        Thread.sleep(5000);
        r.canceled = true;
        System.out.println("发起中断");
    }
}
```

# try/catch，loop为何会影响中断
java线程中断就是基于try/catch的。interrupt只会更改线程的状态。具体的中断业务代码需要自己写
try/catch在loop中，每次都是单独的一次运行，但是将loop放在try/catch中就不一样了

catch住异常不会中断loop
throw异常可以中断loop

