<!-- TOC -->

- [Callable 与 Runnable 区别](#callable-与-runnable-区别)
- [Future](#future)
  - [get](#get)
  - [isDown](#isdown)
  - [isCancelled](#iscancelled)
  - [cancel](#cancel)

<!-- /TOC -->

# Callable 与 Runnable 区别
+ Callable规定的方法是call(),Runnable规定的方法是run().
+ Callable的任务执行后可返回值，而Runnable的任务是不能返回值的
+ call方法可以抛出异常（checked Exception），run方法不可以
+ 运行Callable任务可以拿到一个Future对象，表示异步计算的结果。它提供了检查计算是否完成的方法，以等待计算的完成，并检索计算的结果。通过Future对象可以了解任务执行情况，可取消任务的执行，还可获取执行结果。

```java
@FunctionalInterface
public interface Callable<V> {
    /**
     * Computes a result, or throws an exception if unable to do so.
     *
     * @return computed result
     * @throws Exception if unable to compute a result
     */
    V call() throws Exception;
}


public void futureTest() throws ExecutionException, InterruptedException {
    FutureTask<String> future = new FutureTask<>(() -> "hello future");
    new Thread(future).start();
    System.out.println(future.get());
}
```

# Future
## get
get方法的行为取决于Callable任务的状态，只有以下5种情况：
1. 任务正常完成：get方法会立刻返回结果
2. 任务尚未完成（任务还没开始或进行中）：get将阻塞并直到任务完成
3. 人执行过程中抛出Exception：get方法会抛出ExecutionException，这里的抛出异常，是call()执行时产生的那个异常，看到这个异常类型是java.util.concurrent.ExecutionException。
4. 任务被取消：get方法会抛出CancellationException
5. 任务超时：get方法有一个重载方法，是传入一个延迟时间的，如果时间到了还没有获得结果，get方法就会抛出TimeoutException。

## isDown
判断线程是否执行完毕（执行成功、失败都算完毕）

## isCancelled
是否取消

## cancel
1. 如果这个任务还没有开始执行，那么这种情况最简单，任务会被正常的取消，未来也不会被执行，方法返回true
2. 如果任务已完成，或者已取消：那么cancel()方法会执行失败，方法返回false
3. 如果这个任务已经开始执行了，那么这个取消方法将不会直接取消该任务，而是会根据我们填的参数mayInterruptIfRunning做判断